spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/findmycar
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  jwt:
    secret: dsfadsf
    expiration: 20000
